### ISSUE TITLE
New installation fails: "No default engine was specified..."

### ISSUE THREAD

**Issue by donmccurdy** [now-examples/ghost#4]
After these steps:

```
$ git clone git://github.com/now-examples/ghost
$ cd ghost
$ npm install
$ NODE_ENV=development npm start
```

I'm seeing this message at http://localhost:2368/ghost/, on node 6.9.5 and npm 5.3.0:

```
Error: No default engine was specified and no extension was provided.
    at new View (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/view.js:62:11)
    at EventEmitter.render (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/application.js:570:12)
    at ServerResponse.render (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/response.js:971:7)
    at HTMLErrorRender (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/ghost/core/server/middleware/error-handler.js:86:9)
    at Layer.handle_error (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:315:13)
    at /Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:275:10)
    at prepareError (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/ghost/core/server/middleware/error-handler.js:58:5)
    at Layer.handle_error (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:315:13)
    at /Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:315:13)
    at /Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/router/index.js:275:10)
    at /Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/response.js:424:7
    at SendStream.onerror (/Users/donmccurdy/Documents/Projects/ghost-now-v2/node_modules/express/lib/response.js:1003:5)
```

**Comment by JuanCaicedo** [comment]
I got this error as well, but I think (for me at least) it's stemming from something related to ghost. I see this error below the one posted above
```
ERROR [2018-02-15 10:06:09] "GET /ghost/" 404 26ms

NAME: NotFoundError
CODE: ENOENT
MESSAGE: Resource could not be found.

level:normal

NotFoundError: Resource could not be found.
    at new NotFoundError (/Users/juan/code/personal/personal-site/node_modules/ghost-ignition/lib/errors/index.js:87:23)
    at prepareError (/Users/juan/code/personal/personal-site/node_modules/ghost/core/server/middleware/error-handler.js:35:19)
    at Layer.handle_error (/Users/juan/code/personal/personal-site/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/juan/code/personal/personal-site/node_modules/express/lib/router/index.js:315:13)
    at /Users/juan/code/personal/personal-site/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/juan/code/personal/personal-site/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/juan/code/personal/personal-site/node_modules/express/lib/router/index.js:275:10)
    at Layer.handle_error (/Users/juan/code/personal/personal-site/node_modules/express/lib/router/layer.js:67:12)
    at trim_prefix (/Users/juan/code/personal/personal-site/node_modules/express/lib/router/index.js:315:13)
    at /Users/juan/code/personal/personal-site/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/Users/juan/code/personal/personal-site/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/juan/code/personal/personal-site/node_modules/express/lib/router/index.js:275:10)
    at /Users/juan/code/personal/personal-site/node_modules/express/lib/response.js:424:7
    at SendStream.onerror (/Users/juan/code/personal/personal-site/node_modules/express/lib/response.js:1003:5)
    at emitOne (events.js:96:13)
    at SendStream.emit (events.js:188:7)
    at SendStream.error (/Users/juan/code/personal/personal-site/node_modules/express/node_modules/send/index.js:282:17)
    at SendStream.onStatError (/Users/juan/code/personal/personal-site/node_modules/express/node_modules/send/index.js:433:12)
    at onstat (/Users/juan/code/personal/personal-site/node_modules/express/node_modules/send/index.js:734:26)
    at FSReqWrap.oncomplete (fs.js:123:15)

Error: ENOENT: no such file or directory, stat '/Users/juan/code/personal/personal-site/node_modules/ghost/core/server/admin/views/default.html'
    at Error (native)
```

I think that dev file is missing in the ghost npm package
```
$ ls node_modules/ghost/core/server/admin/views
default-prod.html 
```
I'm going to ask about it in the ghost repo

**Comment by TooTallNate** [comment]
The latest example code is working for me now. If you would like, try it out and let me know if you run into any issues!
